### PR TITLE
Minor fix on zmq_pub and zmq_sub

### LINKED ISSUE #37: Make fails to compile zmq code
On Ubuntu 14.04.4 LTS trusty.

I followed the instruction on .travis.yml

`sudo apt-get install libzmq3-dev`
`wget https://raw.githubusercontent.com/zeromq/cppzmq/master/zmq.hpp`

`lorenzod@lorenzod-hydra-node-01:~/src/hydra/src/main/c/zmq⟫ dpkg --get-selections | grep -v deinstall | grep zmq`
libzmq3:amd64                                   install
libzmq3-dev:amd64                               install

With latest zmq.hpp 
`lorenzod@lorenzod-hydra-node-01:~/src/hydra/src/main/c/zmq⟫ md5sum zmq.hpp` 
27b2b17a2800b80bef2b0248124ff979  zmq.hpp

Make fails:
`lorenzod@lorenzod-hydra-node-01:~/src/hydra/src/main/c/zmq⟫ make`
g++ -std=c++0x -g -I. hdaemon.pb.cc zmq_pub.cc -lzmq -lprotobuf -o ../../scripts/zmq_pub
zmq_pub.cc: In function 'int main()':
zmq_pub.cc:201:5: error: cannot convert 'zmq::socket_t' to 'void_' in initialization
     };
     ^
make: *_\* [../../scripts/zmq_pub] Error 1

I tried to force the cast to void \* (i.e. static_cast<void *>()), but both executables fail.
`lorenzod@lorenzod-hydra-node-01:~/src/hydra/src/main/scripts⟫ ./zmq_sub`
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)

### PR DESCRIPTION
**Pull request by lorenzodavid**
This closes #37 (sushilks/hydra)

Reference: http://stackoverflow.com/questions/32564071/zguide-for-zeromq-fails-compilation

Signed-off-by: Lorenzo David lorenzod@plumgrid.com

### CODE REVIEW

File: src/main/c/zmq/zmq_pub.cc [hunk 1]
```diff
@@ -197,7 +197,7 @@ int main (void) {
   char message_ch[120];
   while(true) {
     zmq_pollitem_t items[] = {
```
Comment (tahir24434) [inline src/main/c/zmq/zmq_pub.cc:199]: I guess if we just install libzmq3-dev and do not copy zmq.hpp of our own, we should be fine.
Let me double check it.

Comment (tahir24434) [inline src/main/c/zmq/zmq_pub.cc:199]: Checked again. This change is required.
